### ISSUE TITLE
column name "ctid" conflicts with a system column name

### ISSUE THREAD

**Issue by yuananf** [treasure-data/prestogres#25]
I tried to get prestogres working on out presto cluster, I followed the install instructions but got problems when running "SELECT \* FROM sys.node";

Error log:
< 2014-12-28 15:26:47.526 CST >LOG:  database system is ready to accept connections
< 2014-12-28 15:26:47.526 CST >LOG:  autovacuum launcher started
< 2014-12-28 15:29:18.971 CST >LOG:  statement: create database "hive"
< 2014-12-28 15:29:19.212 CST >LOG:  statement: create role "hadp" with login
< 2014-12-28 15:29:19.212 CST >ERROR:  role "hadp" already exists
< 2014-12-28 15:29:19.212 CST >STATEMENT:  create role "hadp" with login
< 2014-12-28 15:29:19.213 CST >LOG:  statement: select prestogres_init_database('hadp', 'hive', E'host=\'127.0.0.1\' port=5432 dbname=\'hive\' user=\'prestogres\' password=\'\'')
< 2014-12-28 15:29:19.230 CST >LOG:  statement: do $INIT$ begin
            if not exists (select \* from pg_language where lanname = 'plpythonu') then
                create language plpythonu;
            end if;

```
        if not exists (select * from pg_namespace where nspname = 'prestogres_catalog') then
            create schema prestogres_catalog;
        end if;

        create or replace function prestogres_catalog.start_presto_query(
            presto_server text, presto_user text, presto_catalog text, presto_schema text,
            function_name text, query text)
        returns void as $$
            import prestogres
            prestogres.start_presto_query(
                presto_server, presto_user, presto_catalog, presto_schema, function_name, query)
        $$ language plpythonu
        security definer;

        drop function if exists prestogres_catalog.setup_system_catalog(text, text, text, text);

        create or replace function prestogres_catalog.setup_system_catalog(
            presto_server text, presto_user text, presto_catalog text, presto_schema text,
            access_role text)
        returns void as $$
            import prestogres
            prestogres.setup_system_catalog(
                presto_server, presto_user, presto_catalog, presto_schema, access_role)
        $$ language plpythonu
        security definer;

        revoke temporary on database "hive" from public;  -- reject CREATE TEMPORARY TABLE
        grant usage on schema prestogres_catalog to "hadp";
        grant execute on all functions in schema prestogres_catalog to "hadp";

    end $INIT$ language plpgsql
```

NOTICE:  function prestogres_catalog.setup_system_catalog(text,text,text,text) does not exist, skipping
CONTEXT:  SQL statement "drop function if exists prestogres_catalog.setup_system_catalog(text, text, text, text)"
PL/pgSQL function inline_code_block line 20 at SQL statement
< 2014-12-28 15:29:27.372 CST >LOG:  statement: select 1 from (select prestogres_catalog.setup_system_catalog(E'127.0.0.1:8089', E'hadp', E'hive', E'hive', E'hadp')) s;
< 2014-12-28 15:29:41.244 CST >**ERROR:  spiexceptions.DuplicateColumn: column name "ctid" conflicts with a system column name**
< 2014-12-28 15:29:41.244 CST >CONTEXT:  Traceback (most recent call last):
      PL/Python function "setup_system_catalog", line 4, in <module>
        presto_server, presto_user, presto_catalog, presto_schema, access_role)
      PL/Python function "setup_system_catalog", line 300, in setup_system_catalog
    PL/Python function "setup_system_catalog"

My environment is as follows:
System Version: Linux Centos 6.5
Python Version: 2.6
Presto Version: 0.89
PostgreSQL Version: 9.3.5

Do you have any idea what causes the problem?

**Comment by frsyuki** [comment]
The error message indicates that one of tables has 2 columns with the same name.

"setup_system_catalog " function gets all table information by running "SELECT * FROM information_schema.columns" query on Presto. Then it creates empty tables on PostgreSQL so that clients can get metadata of the tables. If a table has invalid schema such as duplicated column names, setup_system_catalog function fails.

**Comment by frsyuki** [comment]
I added a small workaround to avoid this issue: https://github.com/treasure-data/prestogres/commit/5fe0d534c5e9ad2994222e69c15af088886186ea
It adds "_" at the end of duplicated column names.
The latest Prestogres v0.6.5 includes the improvement.

**Comment by yuananf** [comment]
Thanks, I updated the code, but still face the same problem.
I reinstalled postgresql but it doesn't make any difference.
Do I miss something?

**Comment by frsyuki** [comment]
Could you paste stacktrace shown by Prestogres v0.6.5? At least line number (like `"setup_system_catalog", line 300`) should be changed.

**Comment by yuananf** [comment]
< 2015-01-05 11:00:39.763 CST >LOG:  statement: select 1 from (select prestogres_catalog.setup_system_catalog(E'127.0.0.1:8089', E'hadp', E'hive', E'hive', E'hadp')) s;
< 2015-01-05 11:00:53.062 CST >ERROR:  spiexceptions.DuplicateColumn: column name "ctid" conflicts with a system column name
< 2015-01-05 11:00:53.062 CST >CONTEXT:  Traceback (most recent call last):
      PL/Python function "setup_system_catalog", line 4, in <module>
        presto_server, presto_user, presto_catalog, presto_schema, access_role)
      PL/Python function "setup_system_catalog", line 302, in setup_system_catalog
    PL/Python function "setup_system_catalog"
< 2015-01-05 11:00:53.062 CST >STATEMENT:  select 1 from (select prestogres_catalog.setup_system_catalog(E'127.0.0.1:8089', E'hadp', E'hive', E'hive', E'hadp')) s;
< 2015-01-05 11:00:53.065 CST >LOG:  statement: create database "hive"
< 2015-01-05 11:00:53.066 CST >ERROR:  database "hive" already exists
< 2015-01-05 11:00:53.066 CST >STATEMENT:  create database "hive"
< 2015-01-05 11:00:53.066 CST >LOG:  statement: create role "hadp" with login
< 2015-01-05 11:00:53.066 CST >ERROR:  role "hadp" already exists
< 2015-01-05 11:00:53.066 CST >STATEMENT:  create role "hadp" with login
< 2015-01-05 11:00:53.067 CST >LOG:  statement: select prestogres_init_database('hadp', 'hive', E'host=\'127.0.0.1\' port=5432 dbname=\'hive\' user=\'prestogres\' password=\'\'')

**Comment by frsyuki** [comment]
I found the cause...it's tricky. PostgreSQL reserves some column names for system columns. We can't use them in a table definition.
http://www.postgresql.org/docs/9.3/static/ddl-system-columns.html

I added this change to avoid the error: https://github.com/treasure-data/prestogres/compare/730ff825e60f8642ef0e67c31119dba9dc0b0edc...76e710439b3ff7b88509f581fc104d677857b421
With this change, when a table has reserved column names (such as `ctid`), we can access them with `_` at the end of column names (such as `ctid_`)

I released Prestogres v0.6.6 with the change. Please try it :+1:

**Comment by yuananf** [comment]
It works fine now! Great job!
Thanks!

**Comment by stromal** [comment]
For me exchanging it to ```CTID_``` did not worked but ```NON_CTID``` name has worked.
