### ISSUE TITLE
Cannot connect to Tableau 9.0

### ISSUE THREAD

**Issue by JonathanBennett** [treasure-data/prestogres#29]
When trying to connect to Prestogres using the Postgres adapter in Tableau 9.0 there are no tables retrieved with any combination of details. 

I can see queries being run against Presto, so I know that Tableau is able to connect, however Tableau keeps running the following query over and over; "select table_schema, table_name, column_name, is_nullable, data_type from information_schema.columns". 

Sounds like some of the other issues people have seen. Has anyone managed to get this connected to Tableau 9? (Or indeed more recent 8.x releases where it appeared to have stopped working also?)

**Comment by frsyuki** [comment]
I haven't tried Tableau 9.0.
This ODBC driver slightly-modified for Prestogres might improve the compatibility: https://github.com/treasure-data/prestogres-odbc/wiki

**Comment by JonathanBennett** [comment]
Hi @frsyuki, just to be clear, this is on Mac OS X. I couldn't make it work with Tableau 8.3 either, have you had any good experiences?

**Comment by frsyuki** [comment]
I haven't tried Tableau on Mac (because I don't have license). Does Tableau 8.3 on Mac OS X cause the same problem with Tableau 9.0 (keeps running the same query)?

If Tableau writes log messages to a file, it should be a good start. But I think Tableau doesn't. Another information could be in ODBC driver's log message.

`select table_schema, table_name, column_name, is_nullable, data_type from information_schema.columns` this query gets schema of tables. It is generated by Prestogres when a client connected (code: https://github.com/treasure-data/prestogres/blob/master/prestogres/pgsql/prestogres.py#L242)

A possible cause is that Presto returns different result from PostgreSQL's result. Tableau 9.0 might be causing an internal error because the result is unexpected.
Another possible cause is that an error is happening when Tableau issues a next query. As the result, Tableau could keep reconnecting to Prestogres.
One another possible cause is that the `setup_system_catalog` function (https://github.com/treasure-data/prestogres/blob/master/prestogres/pgsql/prestogres.py#L233) is causing an error. In this case, Prestogres's PostgreSQL or pgpool-II show show error messages.

**Comment by JonathanBennett** [comment]
Hey, yes - Tableau 8.3 causes the same issue and does reissue the query over and over. Tableau does write logs to ~/Documents/My Tableau Repository/Logs, but there doesn't seem to be anything useful in there apart from the following lines;

```
{"ts":"2015-04-07T11:58:32.976","pid":5425,"tid":"254b4","sev":"info","req":"-","sess":"-","site":"-","user":"-","k":"begin-query","v":{"query-hash":2509126948,"query":"show \"lc_collate\"","protocol-id":0}}
{"ts":"2015-04-07T11:58:32.992","pid":5425,"tid":"254b1","sev":"warn","req":"-","sess":"-","site":"-","user":"-","k":"msg","v":"Server error (pid=5456): \n  "}
{"ts":"2015-04-07T11:58:32.992","pid":5425,"tid":"254b1","sev":"warn","req":"-","sess":"-","site":"-","user":"-","k":"msg","v":"See /Users/Jonathan/Documents/My Tableau Repository/Logs/tabprotosrv.txt for details"}
{"ts":"2015-04-07T11:58:32.992","pid":5425,"tid":"254b1","sev":"warn","req":"-","sess":"-","site":"-","user":"-","k":"msg","v":"throw DataSourceException (type=Disconnect): No response from the backend\n"}
{"ts":"2015-04-07T11:58:32.992","pid":5425,"tid":"254b4","sev":"warn","req":"-","sess":"-","site":"-","user":"-","k":"msg","v":"throw DataSourceException (type=Disconnect): No response from the backend\n"}
{"ts":"2015-04-07T11:58:32.992","pid":5425,"tid":"254b4","sev":"info","req":"-","sess":"-","site":"-","user":"-","k":"end-query","v":{"rows":0,"cols":0,"query-hash":2509126948,"query":"show \"lc_collate\"","elapsed":0.015,"protocol-id":0}}
{"ts":"2015-04-07T11:58:32.992","pid":5425,"tid":"254b4","sev":"warn","req":"-","sess":"-","site":"-","user":"-","k":"msg","v":"PostgreSQLConnection:  Unable to discover collation."}
```

With corresponding server logs:

```
{"ts":"2015-04-07T11:58:35.455","pid":5456,"tid":"25f75","sev":"info","req":"-","sess":"-","site":"-","user":"-","k":"connection-info","v":{"info":"ODBCProtocolImpl::Connect: Set 'quiet mode' to prevent driver dialog popups."}}
{"ts":"2015-04-07T11:58:35.455","pid":5456,"tid":"25f75","sev":"info","req":"-","sess":"-","site":"-","user":"-","k":"msg","v":"ODBCProtocol: DBMS Server version: 9.3.6"}
{"ts":"2015-04-07T11:58:35.455","pid":5456,"tid":"25f75","sev":"info","req":"-","sess":"-","site":"-","user":"-","k":"msg","v":"ODBCProtocol: driver version: 09.03.0300"}
{"ts":"2015-04-07T11:58:35.455","pid":5456,"tid":"25f75","sev":"info","req":"-","sess":"-","site":"-","user":"-","k":"msg","v":"ODBCProtocol: driver ODBC version: 03.51"}
{"ts":"2015-04-07T11:58:35.455","pid":5456,"tid":"25f75","sev":"info","req":"-","sess":"-","site":"-","user":"-","k":"msg","v":"ODBCProtocol: ODBC Driver Manager version: 03.52.0000"}
{"ts":"2015-04-07T11:58:35.456","pid":5456,"tid":"25f75","sev":"info","req":"-","sess":"-","site":"-","user":"-","k":"construct-protocol","v":{"created-elapsed":2.458,"id":"6","attributes":{"dbname":"default","server":"54.76.187.107","sslmode":"","username":"pg","password":"","class":"postgres","port":"5439","odbc-connect-string-extras":"","odbc-native-protocol":"yes",":protocol-customizations":"",":thread-session":"0"},"disconnected":false,"created":"07/04/2015 11:58:32 GMT+01:00","this":"0x00007f928082c800"}}
{"ts":"2015-04-07T11:58:35.538","pid":5456,"tid":"25f2e","sev":"warn","req":"-","sess":"-","site":"-","user":"-","k":"msg","v":"ODBCProtocolImpl::EnumerateNames: Note: Unable to enumerate tables without defining table types."}
{"ts":"2015-04-07T11:58:35.538","pid":5456,"tid":"25f2e","sev":"warn","req":"-","sess":"-","site":"-","user":"-","k":"database-error","v":{"retcode-desc":"SQL_ERROR","retcode":-1,"protocol":"7f928082c800","line":5108,"file":"/Volumes/build/builds/tableau-9-0/tableau-9-0.15.0318.1720/modules/connectors/tabmixins/main/db/ODBCProtocolImpl.cpp","error-records":[{"error-record":1,"error-desc":"Error fetching next row","sql-state":"08S01","sql-state-desc":"SQLSTATE_COMMUNICATION_LINK_FAILURE","native-error":26}]}}
{"ts":"2015-04-07T11:58:35.538","pid":5456,"tid":"25f2e","sev":"warn","req":"-","sess":"-","site":"-","user":"-","k":"msg","v":"ODBCProtocolImpl::EnumerateNames: Note: Unable to enumerate tables with explicit table types."}
{"ts":"2015-04-07T11:58:35.538","pid":5456,"tid":"25f2e","sev":"warn","req":"-","sess":"-","site":"-","user":"-","k":"database-error","v":{"retcode-desc":"SQL_ERROR","retcode":-1,"protocol":"7f928082c800","line":5119,"file":"/Volumes/build/builds/tableau-9-0/tableau-9-0.15.0318.1720/modules/connectors/tabmixins/main/db/ODBCProtocolImpl.cpp","error-records":[{"error-record":1,"error-desc":"The cursor is open.","sql-state":"HY010","sql-state-desc":"SQLSTATE_API_FUNCTION_SEQUENCE_ERROR","native-error":3}]}}
{"ts":"2015-04-07T11:58:35.538","pid":5456,"tid":"25f2e","sev":"warn","req":"-","sess":"-","site":"-","user":"-","k":"msg","v":"ODBCProtocolImpl::EnumerateNames: Warning: Unable to fetch qualified names."}
```

It does seem that it's something to do with not receiving something it expected; I can see that the query is issuing a response as I can see it hitting the back end...

Can't find logs for pgpool anywhere (not even stderr) so if there's somewhere I should be looking do let me know!

Thanks for your help.
JB

**Comment by frsyuki** [comment]
Thank you for the error logs.

I guess that Tableau is failing to get the results of the first query. You would be able to know the first query Tableau from pgpool-II's log message (you might need to set `log_statement = on` parameter at prestogres.conf).
I think that the first query is generated by the ODBC driver to get table schema, but might be different. If the query includes BEGIN, DECLARE, or other special SQL commands, you might be able to avoid the error by changing ODBC driver settings.

For example, disabling "Use Declare/Fetch" at this view,

![](http://gyazo.com/76b51cb442fed25423743d3264f9517f.png)

or setting Protocol to 6.4+, Level of rollback on errors to Nop, or disabing Server side prepare:

![](http://gyazo.com/5d4b24401b5fcd7aa9fcc09a09b83462.png)

**Comment by JonathanBennett** [comment]
I don't have that on Mac (advanced settings for ODBC) so I can't change any of those items...

Here's the log from pgpool-II which contains a message saying Prestogres doesn't support extended query with no additional detail. This repeats over and over...

```
2015-04-07 20:58:25: pid 24249: LOG:  new connection received
2015-04-07 20:58:25: pid 24249: DETAIL:  connecting host=82.xxx.xxx.xxx port=58576
2015-04-07 20:58:25: pid 24249: LOG:  statement: select oid, typbasetype from pg_type where typname = 'lo'
2015-04-07 20:58:25: pid 24249: LOG:  DB node id: 0 backend pid: 24301 statement: select 1 from (select prestogres_catalog.setup_system_catalog(E'172.xxx.xxx.xxx:9090', E'pg', E'presto', E'default', E'pg')) s;
2015-04-07 20:58:28: pid 24249: LOG:  DB node id: 0 backend pid: 24301 statement: SELECT count(*) FROM pg_catalog.pg_class AS c WHERE c.relname = 'pg_namespace'
2015-04-07 20:58:28: pid 24249: LOG:  DB node id: 0 backend pid: 24301 statement: SELECT count(*) from (SELECT has_function_privilege('pg', 'to_regclass(cstring)', 'execute') WHERE EXISTS(SELECT * FROM pg_catalog.pg_proc AS p WHERE p.proname = 'to_regclass')) AS s
2015-04-07 20:58:28: pid 24249: LOG:  DB node id: 0 backend pid: 24301 statement: SELECT count(*) from (SELECT has_function_privilege('pg', 'pgpool_regclass(cstring)', 'execute') WHERE EXISTS(SELECT * FROM pg_catalog.pg_proc AS p WHERE p.proname = 'pgpool_regclass')) AS s
2015-04-07 20:58:28: pid 24249: LOG:  DB node id: 0 backend pid: 24301 statement: SELECT count(*) FROM pg_class AS c, pg_namespace AS n WHERE c.relname = 'pg_type' AND c.relnamespace = n.oid AND n.nspname = 'pg_catalog'
2015-04-07 20:58:28: pid 24249: LOG:  DB node id: 0 backend pid: 24301 statement: select oid, typbasetype from pg_type where typname = 'lo'
2015-04-07 20:58:28: pid 24249: LOG:  statement: SET TIMEZONE TO 'UTC'
2015-04-07 20:58:28: pid 24249: LOG:  DB node id: 0 backend pid: 24301 statement: SET TIMEZONE TO 'UTC'
2015-04-07 20:58:28: pid 24249: ERROR:  Parse: Prestogres doesn't support extended query
```

**Comment by frsyuki** [comment]
I see. That's the cause. Prestogres doesn't support extended queries. To disable it, we need to set `UseServerSidePrepare=0` parameter to the ODBC driver. Here is the document: https://github.com/treasure-data/prestogres#limitation

I googled about ODBC on Mac and found some articles:
* "ODBC Administrator Tool" by Apple:
  * https://support.apple.com/kb/DL895?locale=en_US
* "ODBC Manager":
  * http://www.odbcmanager.net/
  * according to FAQ page, Apple stopped including the ODBC Administrator with Mac OS X starting with the release of Mac OS X "Snow Leopard"
* "Configuring a Connector/ODBC DSN on OS X" by MySQL:
  * http://dev.mysql.com/doc/connector-odbc/en/connector-odbc-configuration-dsn-osx.html
* "Creating an ODBC DSN for Macintosh OS X Clients" by Vertica
  * http://my.vertica.com/docs/5.1.6/HTML/index.htm#16715.htm
* "Configuring a Data Source Name (DSN)":
  * http://www.actualtech.com/readme.php

Do some of them work for you?

**Comment by JonathanBennett** [comment]
Hi, no, unfortunately none of those work for me on Mac (namely because Tableau Mac doesn't support custom ODBC connections afaik).

Interestingly, I at least got the database to list out (but not tables) by using the Redshift adapter in Tableau - a step closer than I was using the PostgreSQL driver.

I'm going to raise with Tableau support and see what they recommend, and will get back to this issue when I have more information. 

Thanks for your help so far.

**Comment by JonathanBennett** [comment]
So Tableau helped me with their TDCs and I've managed to successfully connect. Here's a gist of the TDC for anyone who's interested.

https://gist.github.com/JonathanBennett/ea8fcf1b23cefef66869

If you add that to the ~/Documents/My Tableau Repository/Datasources/ folder and then connect through postgres adapter as usual.

Thanks for assistance, @frsyuki.

**Comment by liusztc09** [comment]
Hi @frsyuki I'm trying to connect prestogres using Tableau 9.0, where can I find the default username and password when I try to connect to pgpool since I never created one. I tried several and Tableau said invalid username or pswd. Hope you could help! Thanks a lot!

**Comment by ankitdixit** [comment]
Hi 
I have a similar problem, when trying to connect tableau with prestogres, i am getting the following error in logs: 
 ```ERROR:  Parse: Prestogres doesn't support extended query```
To me it seemes that this is because, prestogres does not support prepared statements, so these are the contents of the file i added in Datasource directory and mentioned by @JonathanBennett .
```<?xml version='1.0' encoding='utf-8' ?>
<connection-customization class='postgres' enabled='true' version='7.7'>
  <vendor name='postgres' />
  <driver name='postgres' />
  <customizations>
    <!-- Keep using the PostgreSQL driver for the Tableau PostgreSQL connection, but override settings that the remote Presto server does not support. -->
    <customization name='odbc-connect-string-extras' value='UseDeclareFetch=0;UseServerSidePrepare=0' />
    <customization name='CAP_CREATE_TEMP_TABLES' value='No' />
    <customization name='CAP_SELECT_INTO' value='No' />
    <customization name='CAP_ODBC_METADATA_SUPPRESS_PREPARED_QUERY' value='yes' />
    <customization name='CAP_ODBC_SUPPRESS_PREPARED_QUERY_FOR_ALL_COMMAND_QUERIES' value='yes' />

 </customizations>
</connection-customization> ```

Still, i am getting the same error. 
Please help
