### ISSUE TITLE
Installing prestogres on AWS

### ISSUE THREAD

**Issue by yixu34** [treasure-data/prestogres#34]
I'm trying to install prestogres on the coordinator of my presto cluster, which is deployed on EMR.  I'm getting a few errors:

1. When I try to install `postgresql93-plpython`:

```
[hadoop@ip-172-18-0-54 ~]$ sudo yum install postgresql93-plpython
Loaded plugins: priorities, update-motd, upgrade-helper
22 packages excluded due to repository priority protections
Resolving Dependencies
--> Running transaction check
---> Package postgresql93-plpython.x86_64 0:9.3.6-2PGDG.rhel7 will be installed
--> Processing Dependency: postgresql93-server(x86-64) = 9.3.6-2PGDG.rhel7 for package: postgresql93-plpython-9.3.6-2PGDG.rhel7.x86_64
--> Processing Dependency: postgresql93(x86-64) = 9.3.6-2PGDG.rhel7 for package: postgresql93-plpython-9.3.6-2PGDG.rhel7.x86_64
--> Finished Dependency Resolution
Error: Package: postgresql93-plpython-9.3.6-2PGDG.rhel7.x86_64 (pgdg93)
           Requires: postgresql93-server(x86-64) = 9.3.6-2PGDG.rhel7
           Installed: postgresql93-server-9.3.6-1.59.amzn1.x86_64 (@amzn-main)
               postgresql93-server(x86-64) = 9.3.6-1.59.amzn1
Error: Package: postgresql93-plpython-9.3.6-2PGDG.rhel7.x86_64 (pgdg93)
           Requires: postgresql93(x86-64) = 9.3.6-2PGDG.rhel7
           Installed: postgresql93-9.3.6-1.59.amzn1.x86_64 (@amzn-main)
               postgresql93(x86-64) = 9.3.6-1.59.amzn1
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
```  
It looks like there is some conflict, where `postgresql93-plpython` requires the standard postgresql package, yet trying to install those packages resolves to the Amazon versions.  I was curious as to how people got around this/if this can be ignored (I suspect it can't).  
2. When I try to do `./configure --program-prefix=prestogres-` (after doing `export PATH=/usr/pgsql-9.3/bin:$PATH`), I get this error:  `configure: error: libpq is not installed or libpq is old`

I searched around, and it looks like I need to install pgpool2.  This results in another error:

```
sudo yum install pgpool-II-93.x86_64
Error: Package: pgpool-II-93-3.4.2-1.rhel7.x86_64 (pgdg93)
          Requires: libmemcached.so.11()(64bit)
Error: Package: pgpool-II-93-3.4.2-1.rhel7.x86_64 (pgdg93)
           Requires: systemd-sysv
Error: Package: pgpool-II-93-3.4.2-1.rhel7.x86_64 (pgdg93)
           Requires: systemd
```

Anyone run into these errors before?

**Comment by frsyuki** [comment]
As long as you can install PostgreSQL >= 9.3 with PL/Python support, you don't have to use postgresql.org's yum repository. You may want to try other sources.

**Comment by yixu34** [comment]
Ah ok, I used a newer AMI and the default AWS repository, and the installation worked.  Thanks!
