### ISSUE TITLE
prestogres-ctl pgpool gives fatal error

### ISSUE THREAD

**Issue by liusztc09** [treasure-data/prestogres#38]
I'm running on AWS EMR, it gives me this error after the command: prestogres-ctl pgpool
[hadoop@ip-XXX-XX-XX-XX pgdata]$ prestogres-ctl pgpool
/usr/local/bin/prestogres-pgpool -n
2015-07-21 04:49:19: pid 20567: FATAL:  initializing pool password, failed to open file:"/usr/local/etc/prestogres_passwd"
2015-07-21 04:49:19: pid 20567: DETAIL:  file open failed with error:"Permission denied"

Has anybody seen this problem?

**Comment by frsyuki** [comment]
Do you have appropriate permission on /usr/local/etc/prestogres_passwd file?

**Comment by liusztc09** [comment]
@frsyuki Thank you for your reply! I got this: -rw-r--r-- 1 root root     0 Jul 20 21:34 prestogres_passwd

**Comment by frsyuki** [comment]
Do you have appropriate permission on /usr, /usr/local and /usr/local/etc directories?

**Comment by frsyuki** [comment]
log says that "initializing pool password". It requires writable permission. It seems that prestogres_password provides write permission only to root. Why don't you give write permission to the execution user?

**Comment by liusztc09** [comment]
@frsyuki It worked after I granted the write permission! Thanks a lot!
